# **Imports**

In [1]:
import numpy as np
from urllib.request import urlopen
import urllib
import matplotlib.pyplot as plt # Visuals
import seaborn as sns 
import sklearn as skl
import pandas as pd
import numpy as np

In [2]:
%pip install pgmpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.9 MB 4.2 MB/s 


In [3]:
%pip install pomegranate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.3 MB 3.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for pomegranate: filename=pomegranate-0.14.8-cp37-cp37m-linux_x86_64.whl size=15068306 sha256=88ea421350274326f47f78b024a769185c6240717930612b7290c69f9715f5bc
  Stored in directory: /root/.cache/pip/wheels/24/68/69/0eaab474ef1d65abedcd47de8a38ab21d221d329954d7edd24
Successfully built pomegranate


In [4]:
import math
from pomegranate import *

In [5]:
# Aplicação de Bayesian Networks
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.models import BayesianModel
from pgmpy.inference import VariableElimination


/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# **1.1 Using Just The 3 Features From Feature Importance**

In [6]:
df_BN = pd.read_csv('heart_cleveland_upload.csv')

df_BN.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   69    1   0       160   234    1        2      131      0      0.1      1   
1   69    0   0       140   239    0        0      151      0      1.8      0   
2   66    0   0       150   226    0        0      114      0      2.6      2   
3   65    1   0       138   282    1        2      174      0      1.4      1   
4   64    1   0       110   211    0        2      144      1      1.8      1   

   ca  thal  condition  
0   1     0          0  
1   2     0          0  
2   0     0          0  
3   1     0          1  
4   0     0          0

In [7]:
model_BM = BayesianModel([('sex','condition'), ('ca','condition'), ('thal','condition')])
model_BM.fit(df_BN,estimator=MaximumLikelihoodEstimator)

/usr/local/lib/python3.7/dist-packages/pgmpy/models/BayesianModel.py:10: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  FutureWarning,


In [8]:
model_BM.nodes()

NodeView(('sex', 'condition', 'ca', 'thal'))

In [9]:
model_BM.edges()

OutEdgeView([('sex', 'condition'), ('ca', 'condition'), ('thal', 'condition')])

# **1.2 Inferencing with Bayesian Network**

In [10]:
HeartDiseasetest_infer = VariableElimination(model_BM)


print('\nProbability of HeartDisease given evidence = (sex = 0)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'sex':0})
print(q)

print('\nProbability of HeartDisease given evidence = (sex = 1)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'sex':1})
print(q)

print('\nProbability of HeartDisease given evidence = (ca = 0)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'ca':0})
print(q)

print('\nProbability of HeartDisease given evidence = (ca = 1)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'ca':1})
print(q)

print('\nProbability of HeartDisease given evidence = (ca = 2)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'ca':2})
print(q)

print('\nProbability of HeartDisease given evidence = (ca = 3)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'ca':3})
print(q)

print('\nProbability of HeartDisease given evidence = (thal = 0)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'thal':0})
print(q)

print('\nProbability of HeartDisease given evidence = (thal = 1)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'thal':1})
print(q)

print('\nProbability of HeartDisease given evidence = (thal = 2)')
q=HeartDiseasetest_infer.query(variables=['condition'],evidence={'thal':2})
print(q)



Probability of HeartDisease given evidence = (sex = 0)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.5478 |
+--------------+------------------+
| condition(1) |           0.4522 |
+--------------+------------------+

Probability of HeartDisease given evidence = (sex = 1)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.4920 |
+--------------+------------------+
| condition(1) |           0.5080 |
+--------------+------------------+

Probability of HeartDisease given evidence = (ca = 0)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.6807 |
+--------------+------------------+
| condition(1) |           0.3193 |
+--------------+------------------+

Probability of HeartDisease given evidence = (ca = 1)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.3263 |
+--------------+------------------+
| condition(1) |           0.6737 |
+--------------+------------------+

Probability of HeartDisease given evidence = (ca = 2)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.2361 |
+--------------+------------------+
| condition(1) |           0.7639 |
+--------------+------------------+

Probability of HeartDisease given evidence = (ca = 3)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.1428 |
+--------------+------------------+
| condition(1) |           0.8572 |
+--------------+------------------+

Probability of HeartDisease given evidence = (thal = 0)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.6930 |
+--------------+------------------+
| condition(1) |           0.3070 |
+--------------+------------------+

Probability of HeartDisease given evidence = (thal = 1)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.4383 |
+--------------+------------------+
| condition(1) |           0.5617 |
+--------------+------------------+

Probability of HeartDisease given evidence = (thal = 2)


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.2604 |
+--------------+------------------+
| condition(1) |           0.7396 |
+--------------+------------------+


# **1.3 Dividing Test and Training Set To Check Accuracy**

In [11]:
ds = pd.read_csv('dataset.csv', header= None)
data = ds.iloc[:, [-1, 1, -2, -3]].values

print(data)
print(data.shape)

[[0 1 0 1]
 [0 0 0 2]
 [0 0 0 0]
 ...
 [1 1 2 0]
 [0 0 0 0]
 [1 1 2 0]]
(297, 4)


In [12]:
# Train and data split - 80% - 20%
train = data[1:237]
test = data[238:]

In [16]:
opt=1 # Quando corrido pela primeira vez correr com opt=0 e depois opt=1

if opt==1:
  model = BayesianNetwork.from_samples(train)
if opt==0:
  df_train = pd.DataFrame(train,columns=['A','B','C','D'])

# A - condition
# B - sex
# C - ca
# D - thal


B = DiscreteDistribution( {0: df_train[df_train.B==0].shape[0]/df_train.shape[0],1:df_train[df_train.B==1].shape[0]/df_train.shape[0]})
C = DiscreteDistribution( {0: df_train[df_train.C==0].shape[0]/df_train.shape[0],1:df_train[df_train.C==1].shape[0]/df_train.shape[0],
                         2:df_train[df_train.C==2].shape[0]/df_train.shape[0], 3:df_train[df_train.C==3].shape[0]/df_train.shape[0]})
D = DiscreteDistribution( {0: df_train[df_train.D==0].shape[0]/df_train.shape[0],1:df_train[df_train.D==1].shape[0]/df_train.shape[0], 
                           2:df_train[df_train.D==2].shape[0]/df_train.shape[0]})

In [18]:
row = train[0]

obs = {'B' : row[1], 'C' : row[2], 'D' : row[3]}
pa = model.predict_proba(obs)[0].parameters[0][1]

print('Probabilidade do A ser 1: ', pa)

pA = model.predict_proba(obs)[0].parameters[0]

reala  = row[0]

Probabilidade do A ser 1:  0.41101694915254233


In [19]:
from sklearn.metrics import classification_report

def predict(train,w=0.5):

  lst_real = []
  lst_pred = []

  for row in train:
      obs = {'B' : row[1], 'C' : row[2], 'D' : row[3]}
      pa = model.predict_proba(obs)[0].parameters[0][1]
      realA  = row[0]
      predA = 0
      if pa > w:
          predA = 1

      lst_pred.append(predA)
      lst_real.append(realA)

  print(lst_real,lst_pred)
  print(classification_report(lst_real,lst_pred))
  return 

predict(train)

[0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
from sklearn.metrics import confusion_matrix

def cm(train,w=0.5):

  lst_real = []
  lst_pred = []

  for row in train:
      obs = {'B' : row[1], 'C' : row[2], 'D' : row[3]}
      pa = model.predict_proba(obs)[0].parameters[0][1]
      realA  = row[0]
      predA = 0
      if pa > w:
          predA = 1

      lst_pred.append(predA)
      lst_real.append(realA)

  confm = confusion_matrix(lst_real,lst_pred)
  print(confm)

  return confm

# Compute confusion matrix
confm = cm(test)
print('Confusion matrix - Bayesian Natework')
#print(cm_test)

print()

#Test set
L = 59
ACC = (confm[0][0] + confm[1][1]) / L
PREC = (confm[0][0])/ (confm[0][0]+ confm[1][0])
TPR = (confm[0][0]) / (confm[0][0] + confm[0][1])
TNR = (confm[1][1])/ (confm[1][1] + confm[1][0])
FPR = 1-TNR
REC = (confm[0][0])/ (confm[0][0] + confm[0][1])
F1SCORE = 2 * (REC * PREC)/(REC+PREC)
BAL_ACC = (REC+TNR)/2

print('Accuracy for test set = ', ACC)
print('Precision for test = ', PREC)
print('True Positive Rate = ', TPR)
print('True Negative Rate = ', TNR)
print('False Positive Rate = ', FPR)
print('Recall = ', REC)
print('F1 Score = ', F1SCORE)
print('Balanced Accuracy = ',BAL_ACC)

[[20  0]
 [39  0]]
Confusion matrix - Bayesian Natework

Accuracy for test set =  0.3389830508474576
Precision for test =  0.3389830508474576
True Positive Rate =  1.0
True Negative Rate =  0.0
False Positive Rate =  1.0
Recall =  1.0
F1 Score =  0.5063291139240507
Balanced Accuracy =  0.5


# **2.1 Importing The Data Set and Customizing**

In [21]:
import pandas as pd

heartDisease = pd.read_csv('heart_cleveland_upload.csv')

del heartDisease['ca']
del heartDisease['slope']
del heartDisease['thal']
del heartDisease['oldpeak']

heartDisease = heartDisease.replace('?', np.nan)
heartDisease.dtypes
heartDisease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  condition
0   69    1   0       160   234    1        2      131      0          0
1   69    0   0       140   239    0        0      151      0          0
2   66    0   0       150   226    0        0      114      0          0
3   65    1   0       138   282    1        2      174      0          1
4   64    1   0       110   211    0        2      144      1          0

# **2.2 Modeling The Data Set**

In [22]:
model = BayesianModel([('age', 'trestbps'), ('age', 'fbs'), ('sex', 'trestbps'), ('sex', 'trestbps'), 
                       ('exang', 'trestbps'),('trestbps','condition'),('fbs','condition'),
                      ('condition','restecg'),('condition','thalach'),('condition','chol')])

# Learing CPDs using Maximum Likelihood Estimators
model.fit(heartDisease, estimator=MaximumLikelihoodEstimator)



/usr/local/lib/python3.7/dist-packages/pgmpy/models/BayesianModel.py:10: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  FutureWarning,


In [23]:
print(model.get_cpds('age'))

+---------+------------+
| age(29) | 0.003367   |
+---------+------------+
| age(34) | 0.00673401 |
+---------+------------+
| age(35) | 0.013468   |
+---------+------------+
| age(37) | 0.00673401 |
+---------+------------+
| age(38) | 0.003367   |
+---------+------------+
| age(39) | 0.013468   |
+---------+------------+
| age(40) | 0.010101   |
+---------+------------+
| age(41) | 0.03367    |
+---------+------------+
| age(42) | 0.026936   |
+---------+------------+
| age(43) | 0.023569   |
+---------+------------+
| age(44) | 0.037037   |
+---------+------------+
| age(45) | 0.026936   |
+---------+------------+
| age(46) | 0.023569   |
+---------+------------+
| age(47) | 0.016835   |
+---------+------------+
| age(48) | 0.023569   |
+---------+------------+
| age(49) | 0.016835   |
+---------+------------+
| age(50) | 0.023569   |
+---------+------------+
| age(51) | 0.040404   |
+---------+------------+
| age(52) | 0.037037   |
+---------+------------+
| age(53) | 0.023569   |


In [24]:
print(model.get_cpds('chol'))

+-----------+--------------+-----------------------+
| condition | condition(0) | condition(1)          |
+-----------+--------------+-----------------------+
| chol(126) | 0.00625      | 0.0                   |
+-----------+--------------+-----------------------+
| chol(131) | 0.0          | 0.0072992700729927005 |
+-----------+--------------+-----------------------+
| chol(141) | 0.00625      | 0.0                   |
+-----------+--------------+-----------------------+
| chol(149) | 0.00625      | 0.0072992700729927005 |
+-----------+--------------+-----------------------+
| chol(157) | 0.00625      | 0.0                   |
+-----------+--------------+-----------------------+
| chol(160) | 0.00625      | 0.0                   |
+-----------+--------------+-----------------------+
| chol(164) | 0.0          | 0.0072992700729927005 |
+-----------+--------------+-----------------------+
| chol(166) | 0.0          | 0.0072992700729927005 |
+-----------+--------------+------------------

In [25]:
print(model.get_cpds('sex'))

+--------+----------+
| sex(0) | 0.323232 |
+--------+----------+
| sex(1) | 0.676768 |
+--------+----------+


In [26]:
model.get_independencies()

(age ⟂ sex, exang)
(age ⟂ sex, exang | fbs)
(age ⟂ exang | sex)
(age ⟂ sex | exang)
(age ⟂ thalach, restecg, chol | condition)
(age ⟂ thalach, chol | condition, restecg)
(age ⟂ restecg, chol | thalach, condition)
(age ⟂ thalach, condition, restecg, chol | trestbps, fbs)
(age ⟂ thalach, restecg, chol | trestbps, condition)
(age ⟂ exang | sex, fbs)
(age ⟂ sex | exang, fbs)
(age ⟂ thalach, restecg, chol | condition, fbs)
(age ⟂ thalach, restecg | condition, chol)
(age ⟂ thalach, restecg, chol | sex, condition)
(age ⟂ thalach, restecg, chol | exang, condition)
(age ⟂ chol | thalach, condition, restecg)
(age ⟂ thalach, condition, chol | trestbps, restecg, fbs)
(age ⟂ thalach, chol | trestbps, condition, restecg)
(age ⟂ thalach, chol | condition, restecg, fbs)
(age ⟂ thalach | condition, restecg, chol)
(age ⟂ thalach, chol | sex, condition, restecg)
(age ⟂ thalach, chol | exang, condition, restecg)
(age ⟂ condition, restecg, chol | thalach, trestbps, fbs)
(age ⟂ restecg, chol | thalach, tres

In [27]:
model.nodes()

NodeView(('age', 'trestbps', 'fbs', 'sex', 'exang', 'condition', 'restecg', 'thalach', 'chol'))

In [28]:
model.edges()

OutEdgeView([('age', 'trestbps'), ('age', 'fbs'), ('trestbps', 'condition'), ('fbs', 'condition'), ('sex', 'trestbps'), ('exang', 'trestbps'), ('condition', 'restecg'), ('condition', 'thalach'), ('condition', 'chol')])

# **2.3 Inferencing with Bayesian Network**

In [29]:
# Doing exact inference using Variable Elimination
from pgmpy.inference import VariableElimination
HeartDisease_infer = VariableElimination(model)

q = HeartDisease_infer.query(variables=['condition'], evidence={'age': 29})
print(q)

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.6042 |
+--------------+------------------+
| condition(1) |           0.3958 |
+--------------+------------------+


# **2.4 Prints**

In [30]:
print(model)

BayesianModel with 9 nodes and 9 edges


In [31]:
model.edges()

OutEdgeView([('age', 'trestbps'), ('age', 'fbs'), ('trestbps', 'condition'), ('fbs', 'condition'), ('sex', 'trestbps'), ('exang', 'trestbps'), ('condition', 'restecg'), ('condition', 'thalach'), ('condition', 'chol')])

In [32]:
model.nodes()

NodeView(('age', 'trestbps', 'fbs', 'sex', 'exang', 'condition', 'restecg', 'thalach', 'chol'))

In [33]:
model.get_cpds()

[<TabularCPD representing P(age:41) at 0x7f497cf26a50>,
 <TabularCPD representing P(trestbps:50 | age:41, exang:2, sex:2) at 0x7f497cf829d0>,
 <TabularCPD representing P(fbs:2 | age:41) at 0x7f497c8afcd0>,
 <TabularCPD representing P(sex:2) at 0x7f497cf26ad0>,
 <TabularCPD representing P(exang:2) at 0x7f497cf3c610>,
 <TabularCPD representing P(condition:2 | fbs:2, trestbps:50) at 0x7f497d015a50>,
 <TabularCPD representing P(restecg:3 | condition:2) at 0x7f497cf3c690>,
 <TabularCPD representing P(thalach:91 | condition:2) at 0x7f497d045b50>,
 <TabularCPD representing P(chol:152 | condition:2) at 0x7f497d072790>]

# **3 Inferencing with Bayesian Network With Inputs**

In [35]:
model = BayesianModel([('age', 'trestbps'), ('age', 'fbs'), ('sex', 'trestbps'), ('sex', 'trestbps'), 
                       ('exang', 'trestbps'),('trestbps','condition'),('fbs','condition'),
                      ('condition','restecg'),('condition','thalach'),('condition','chol')])

print('For age Enter [29,77]')
print('For sex Enter { Male:1, Female:0 }')
print('For Exercise induced angima { Yes:1, No:0 }')
print('For Fasting blood sugar > 120 mg/d Enter { Yes:1, No:0 }')

q = HeartDisease_infer.query(variables=['condition'], evidence={
    'age':int(input('Enter age :')),
    'sex':int(input('Enter sex :')),
    'exang':int(input('Enter Exercise induced angima :')),
    'fbs':int(input('Enter Fasting blood sugar :'))
    })

print(q)

/usr/local/lib/python3.7/dist-packages/pgmpy/models/BayesianModel.py:10: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  FutureWarning,


For age Enter [29,77]
For sex Enter { Male:1, Female:0 }
For Exercise induced angima { Yes:1, No:0 }
For Fasting blood sugar > 120 mg/d Enter { Yes:1, No:0 }
Enter age :30
Enter sex :0
Enter Exercise induced angima :0
Enter Fasting blood sugar :0


/usr/local/lib/python3.7/dist-packages/pgmpy/factors/discrete/DiscreteFactor.py:542: UserWarning: Found unknown state name. Trying to switch to using all state names as state numbers
  UserWarning,


  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.6086 |
+--------------+------------------+
| condition(1) |           0.3914 |
+--------------+------------------+
